# Site variables
title:       PDF Library
description: A website that allows users to conveniently store and view PDF books and sheet music.

url:       'www.weitungchen.com'
baseUrl:   '/web-chess'
pluginUrl: 'https://weitungchen.com/plugins'

# Build settings
markdown: kramdown
theme:    minima
